name: 'StackQL Studios - StackQL Assert'
description: 'run StackQL query to test and audit your infrastructure.'
author: 'Yuncheng Yang, StackQL Studios'
inputs:
  auth_obj_path:
    description: file path to json object of stackql auth
    required: false
  auth_str:
    description: json string of stackql auth
    required: false
  test_query:
    description: stackql query to be executed
    required: false
  test_query_file_path:
    description: stackql query file to be executed
    required: false
  expected_rows: 
    description: expected number of rows from executing test query
    required: false
  expected_results_str:
    description: expected result from executing test query, support json string, overrides expected_results_file_path
    required: false
  expected_results_file_path:
    description: file that stores expected result, json is support
    required: false

runs:
  using: "composite"
  steps:
    - name: Check StackQL is installed and set output
      id: check-stackql
      shell: bash
      run: |
        if command -v stackql &> /dev/null; then
            echo "stackql_installed=true" >> $GITHUB_OUTPUT
        else
            echo "stackql_installed=false" >> $GITHUB_OUTPUT
        fi

        
    - name: Setup StackQL
      uses: stackql/setup-stackql@v1.1.0
      if: ${{steps.check-stackql.outputs.stackql_installed == 'false'}}
      with:
        use_wrapper: true

    - name: Setup auth
      id: setup-auth
      uses: actions/github-script@v6
      with:
        script: |
          const path = require('path');
          const utilsPath = path.join(process.env.GITHUB_ACTION_PATH, 'lib', 'utils.js')
          const {setupAuth} = require(utilsPath)
          setupAuth(core)
      env:
        AUTH_FILE_PATH: ${{ inputs.auth_obj_path }}
        AUTH_STR: ${{inputs.auth_str}}

    - name: get stackql command
      uses: actions/github-script@v6
      with:
        script: |
          const path = require('path');
          const utilsPath = path.join(process.env.GITHUB_ACTION_PATH, 'lib', 'utils.js')
          const {getStackqlCommand} = require(utilsPath)
          getStackqlCommand(core)
      env:
        QUERY_FILE_PATH: ${{ inputs.test_query_file_path }}
        QUERY: ${{inputs.test_query}}
        OUTPUT: 'json'
    
    - name: execute stackql command
      id: exec-query
      shell: bash
      run: |
        ${{ env.STACKQL_COMMAND }}
    
    - name: Check results
      uses: actions/github-script@v6
      with:
        script: |
          const path = require('path');
          const assertPath = path.join(process.env.GITHUB_ACTION_PATH, 'stackql-assert.js')
          const {assertResult} = require(assertPath)
          assertResult(core)
      env:
        RESULT: ${{steps.exec-query.outputs.stdout}}
        EXPECTED_RESULTS_STR: ${{ inputs.expected_results_str }}
        EXPECTED_RESULTS_FILE_PATH: ${{inputs.expected_results_file_path}}
        EXPECTED_ROWS: ${{inputs.expected_rows}}


    
      
branding:
  icon: 'terminal'
  color: 'green'