name: 'stackql-assert'
description: 'Run StackQL query to test and audit your infrastructure.'
author: 'Yuncheng Yang, StackQL Studios'
inputs:
  test_query:
    description: 'StackQL query to execute (supply either test_query or test_query_file_path)'
    required: false
  test_query_file_path:
    description: 'StackQL query file to execute (supply either test_query or test_query_file_path)'
    required: false
  data_file_path:
    description: 'Path to data file to pass to the StackQL query preprocessor (JSON or Jsonnet file)'
    required: false
  vars:
    description: 'Comma delimited list of variables to pass to the StackQL query preprocessor (supported with Jsonnet config blocks or Jsonnet data files only)'
    required: false
  expected_rows:
    description: 'Expected number of rows from executing test query'
    required: false
  expected_results_str:
    description: 'Expected result (as a JSON string) from executing test query, overrides expected_results_file_path'
    required: false
  expected_results_file_path:
    description: 'JSON file with the expected result'
    required: false
  auth_obj_path:
    description: 'Path of JSON file that stores StackQL AUTH string (only required when using non-standard environment variable names)'
    required: false
  auth_str:
    description: 'StackQL AUTH string (only required when using non-standard environment variable names)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup StackQL
      uses: stackql/setup-stackql@v2.2.1
      with:
        use_wrapper: true

    - name: Execute StackQL Command
      id: exec-query
      uses: stackql/stackql-exec@v2.2.1
      with:
        query: ${{ inputs.test_query }}
        query_file_path: ${{ inputs.test_query_file_path }}
        data_file_path: ${{ inputs.data_file_path }}
        vars: ${{ inputs.vars }}
        auth_obj_path: ${{ inputs.auth_obj_path }}
        auth_str: ${{ inputs.auth_str }}
        dry_run: false

    - name: Check Results
      uses: actions/github-script@v7.0.1
      with:
        script: |
          const path = require('path');
          const assertPath = path.join(process.env.GITHUB_ACTION_PATH, 'lib', 'assert.js')
          const {assertResult} = require(assertPath)
          assertResult(core)
      env:
        RESULT: ${{ steps.exec-query.outputs.stackql-query-results }}
        EXPECTED_RESULTS_STR: ${{ inputs.expected_results_str }}
        EXPECTED_RESULTS_FILE_PATH: ${{ inputs.expected_results_file_path }}
        EXPECTED_ROWS: ${{ inputs.expected_rows }}

branding:
  icon: 'terminal'
  color: 'blue'
